version: "3.9"
services:
  us-east-1:
    environment:
      - REGION=us-east-1
    build:
      context: .

  us-west-1:
    environment:
      - REGION=us-west-1
    build:
      context: .

  eu-west-1:
    environment:
      - REGION=eu-west-1
    build:
      context: .
    ports:
      - '5000:5000'

  pyroscope:
    image: pyroscope/pyroscope
    ports:
      - '4040:4040'
    command:
      - 'server'

  load-generator:
    build:
      context: .
      dockerfile: Dockerfile.load-generator
